#!/bin/bash

set -u
set -e

# Ask the user to select an image generated by the OpenWrt build system
echo "Select a valid release image in the following list:"
select file in $(find ./ReleaseImage -name '*.img')
do
    IMG_FILE_PATH="$(realpath "${file}")"
    break
done

# Select a block device to write the image into:
echo "Select a block device to write the image into:"
select dev in $(lsblk --raw --paths --nodeps --noheadings -o NAME)
do
    BLOCK_DEV="${dev}"
    break
done

# Inspect the disk to make sure the user picked the right one:
lsblk --output 'PATH,FSTYPE,FSVER,MOUNTPOINT,LABEL,PTTYPE,PARTTYPE,PARTTYPENAME,PARTFLAGS,SERIAL,SIZE,STATE,TYPE,TRAN,SUBSYSTEMS,VENDOR' "${BLOCK_DEV}"
read -p "Review the above disk info to verify that the correct disk has been selected."
read -p "Are you really sure the correct disk has been selected???"

# Force the user to type their password:
sudo --reset-timestamp true

# Write the image:
set -x
sudo dd status=progress conv=fsync bs=2M count=1 "if=/dev/zero" "of=${BLOCK_DEV}"
time sudo dd status=progress conv=fsync bs=2M "if=${IMG_FILE_PATH}" "of=${BLOCK_DEV}"
sync
